language: objective-c

before_script: 
- gem install xcpretty
- gem update cocoapods
- echo -e "#define PARSE_APP_ID @\"fun\"\n#define PARSE_CLIENT_ID @\"world\"" > OnionStorage/OCParseConstants.h
- export LANG=en_US.UTF-8

script:
- xcodebuild -project OnionStorage.xcodeproj -scheme OnionStorage -sdk iphonesimulator test | xcpretty -c