language: objective-c

before_script: 
- echo -e "#define PARSE_APP_ID @\"fun\"\n#define PARSE_CLIENT_ID @\"world\"" > OnionStorage/ParseConstants.h

script:
- xctool ARCHS=i386 ONLY_ACTIVE_ARCH=NO -project OnionStorage.xcodeproj -scheme OnionStorage -sdk iphonesimulator clean build test -freshSimulator -freshInstall